### ISSUE TITLE
Feature Request: Add Align Setting

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-UltimakerFormatPackage#11]
> The selector should be something like `div.inline_thumbnail > img` I would think.

could it be possible to add an "align" setting? I will place the thumbnail at the right side of file list but themify does not handle my change well. only one time when I set it up it is in the right position. after refresh it is in the old position.

_Originally posted by @TAOGde in https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/issues/3#issuecomment-593071209_

**Comment by TAOGde** [comment]
well this does noting to the image here.
align or width not working.

**Comment by jneilliii** [comment]
@TaoGde, I was just enabling Themify to test.  Did you try float?

**Comment by jneilliii** [comment]
That doesn't seem to work either.  I think it's because Themify doesn't apply the css live, so newly added DOM elements (async file list for example) aren't getting the setting added to Themify. I'll add a setting to apply the float option to handle alignment, shouldn't be too difficult.

**Comment by TAOGde** [comment]
> @TAOGde, I was just enabling Themify to test. Did you try float?

i tryed but nothing changed. I post2 screenshots with this part.
the second screenshot is with hardcoded align="right" before your width="30%" entry.
<img width="1819" alt="hardcoded align= right" src="https://user-images.githubusercontent.com/43980652/75630582-466a4300-5bec-11ea-8ceb-45bfa513e9ec.png">
<img width="1819" alt="nothing changed" src="https://user-images.githubusercontent.com/43980652/75630583-4b2ef700-5bec-11ea-88b9-e1cc64220baf.png">

**Comment by jneilliii** [comment]
Ok, I just pushed a new branch, 0.1.4.  You can install from the URL below in plugin manager.  Give it a try and let me know how the alignment option works for you.

https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/archive/0.1.4.zip

**Comment by TAOGde** [comment]
> Ok, I just pushed a new branch, 0.1.4. You can install from the URL below in plugin manager. Give it a try and let me know how the alignment option works for you.
> 
> https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/archive/0.1.4.zip

this works :) TNX

i will try to set the thumbnail as background so the text can float on the left space ;) I give report back :)

**Comment by jneilliii** [comment]
That unfortunately probably won't work because the image is contained within a div that has a class of `row-fluid` which is blocking and set for 100% width..
