### ISSUE TITLE
Uploaded UFP file not deleted from Plugin-Folder

### ISSUE THREAD

**Issue by OllisGit** [jneilliii/OctoPrint-UltimakerFormatPackage#13]
Hi @jneilliii ,
I am starting analysing the "[remove thumbnail-issue](https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/issues/11)".
So, I tested a "normal" case:
- Upload the ufp-file
- The ufp file is uploaded to  "data/UltimakerFormatPackage/"
- Its extract to the data folder and the gcode-file is copied to uploads/folder

fine....but after deleting the gcode from the GUI, all files where delete, except the orig. ufp file.

Tested with: 1.4.0rc5, Python 2.7

Could you reproduce this behaviour?

BTW. Why do you store the gocde and ufp file in your plugin folder...it waste harddisc-space?

After upload:
![image](https://user-images.githubusercontent.com/24205767/77230432-66aa7380-6b94-11ea-9981-d296c3cc95ad.png)

After delete:
![image](https://user-images.githubusercontent.com/24205767/77230438-7033db80-6b94-11ea-917a-a5402a2176af.png)

**Comment by jneilliii** [comment]
No particular reason specifically that I remember, just an oversight.

**Comment by jneilliii** [comment]
Just an oversight @OllisGit. It was my assumption that the [DiskFileWrapper](https://docs.octoprint.org/en/master/modules/filemanager.html#octoprint.filemanager.util.DiskFileWrapper) based on the docs moved the file instead of copy the file.

**Comment by jneilliii** [comment]
Should be fixed with commit https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/commit/a66166bd089fb8709df804d6c8a82d6dc8f77f3c and added to next release version #12

**Comment by OllisGit** [comment]
Morning @jneilliii ,

I tested the 0.1.4 branch. 
- Removing the file via UI is now removing completely all files
- But why do you still keep the ufp.gcode file in the plugin folder. It is redundant and not needed (IMHO)

I tested also the [FileManager](https://plugins.octoprint.org/plugins/filemanager/) plugin for moving gcode to a sub-folder. 
Unfortunately only the remove-event is passing the UFP-Plugin, the "FileAdded" event doesn't occourse....I think to solve the move image-issue (a.k.a. additional metadata), we need to analyse/improve the Octoprint-Core code or patching all plugins which were using file move.

**Comment by jneilliii** [comment]
Again, I thought the removal of the source file was handled properly by the DiskWrapper [here](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/blob/a66166bd089fb8709df804d6c8a82d6dc8f77f3c/octoprint_ultimakerformatpackage/__init__.py#L101), but I guess not. I'll have to add the manual removal. I didn't even think about the FileManager doing this too since I don't use it.

**Comment by jneilliii** [comment]
Just pushed another commit that also removes the gcode file from the plugin's data folder.
