### ISSUE TITLE
In-line images not working

### ISSUE THREAD

**Issue by CasketPizza** [jneilliii/OctoPrint-UltimakerFormatPackage#15]
I can't seem to get thumbnails showing in the list with themify. I get the icon with the pop-up but no luck with them added to the list.
I disabled my other layout edits and still no luck.
Would really appreciate help <3
![image](https://user-images.githubusercontent.com/29517500/79972668-aa690380-84d9-11ea-97bb-501ce1716a9c.png)

![image](https://user-images.githubusercontent.com/29517500/79972787-d4222a80-84d9-11ea-8870-db277300d485.png)

**Comment by jneilliii** [comment]
Go into settings and turn on the inline thumbnail option.
