### ISSUE TITLE
How to save .ufp.gcode from Cura (4.6)?

### ISSUE THREAD

**Issue by leoheck** [jneilliii/OctoPrint-UltimakerFormatPackage#19]
First of all, this plugin is awesome, thank you.

Everything is working just fine using `Print with octoprint` button. My doubt is, how do I save this `.ufp.gcode` instead of printing directly with octoprint? I saw it generates something different than saving as `.ufp`

**Comment by leoheck** [comment]
I see you use the .upf to get the image and the gcode all at once. clever! So I just have to save the .upf file and use it when I need to work like this.

**Comment by jneilliii** [comment]
There's also the octoprint connection plugin to cura that will give you one click printing directly to octoprint and supports the ufp file format if this plugin is detected.

**Comment by leoheck** [comment]
> There's also the octoprint connection plugin to cura that will give you one click printing directly to octoprint and supports the ufp file format if this plugin is detected.

Yes yes,  that is what I said in the first comment. I use this a lot at home with my printer.

But at my work, I have to store the files before sending them to print. So, right now I am storing this .ufp instead of .gcode since it is just a package. Now, I have another problem is that I upload (many files) them with ssh instead of just using octoprint website.

So, my second question is. What you are doing with this plugin so I can mimic it from the command line? You send the .ufp, then unpack it then, rename the gcode, where is the picture? Where the picture will be stored? Can you explain this to me?

So, they are stored here, right?
`/home/pi/.octoprint/data/UltimakerFormatPackage`

**Comment by leoheck** [comment]
Your plugin has any way to run it from the command line passing the .ufp and then it does the job?

**Comment by leoheck** [comment]
Adding the .ufp and the .png in the `/home/pi/.octoprint/data/UltimakerFormatPackage` dind't work as I was expecting.

**Comment by jneilliii** [comment]
> Your plugin has any way to run it from the command line passing the .ufp and then it does the job?

Transferring files outside of API or via the web interface (which also uses API on the backend) should be done to the watched folder. That way the "normal" file processing occurs on those by the system. This is all in theory though as I have not yet tried it. So from Cura you save your sliced file as ufp format and then SSH transfer your file into the watched folder. If that doesn't work then there may be a bug in the core OctoPrint where it doesn't take into account custom file extensions like it does in the web interface.

**Comment by jneilliii** [comment]
I just tested my theory and it does work as expected on my pi, but not in windows for some reason. So yeah, slice, save your file as ufp format, upload/transfer to the watched folder.

![image](https://user-images.githubusercontent.com/5249455/80547305-dd9e0d80-8985-11ea-882b-48f013ce5561.png)

**Comment by leoheck** [comment]
Awesome, this `/home/pi/.octoprint/watched` works, thank you.

Do you know if it is possible to organize files in a folder? Adding a folder to the watched does not work.

**Comment by leoheck** [comment]
Ah, maybe it is not possible yet since it is an open request
https://github.com/OctoPrint/OctoPrint/issues/2451

**Comment by jneilliii** [comment]
Correct, it's not currently possible.
