### ISSUE TITLE
Updating to 0.1.7 broke Automatic start print job after uploading

### ISSUE THREAD

**Issue by sidhant** [jneilliii/OctoPrint-UltimakerFormatPackage#20]
After updating to 0.1.7 release, I have not been able to print from Cura. I get the following error:
![CuraError](https://user-images.githubusercontent.com/680782/80831740-39dc7980-8ba0-11ea-8838-4c048967a8b3.jpg)

Edit (so search engines can find it): 
OctoPrint Error
File not found on 'local'
filename.ufp.gcode

`
2020-05-01 11:43:56,402 - octoprint.filemanager.analysis - INFO - Starting analysis of local:UM2_e9c07069-442e-4a07-90b2-ac8281bf0859.gcode
2020-05-01 11:43:56,407 - octoprint.filemanager.analysis - INFO - Invoking analysis command: /home/pi/oprint/bin/python2 -m octoprint analysis gcode --speed-x=6000 --speed-y=6000 --max-t=10 --throttle=0.0 --throttle-lines=100 /home/pi/.octoprint/uploads/UM2_e9c07069-442e-4a07-90b2-ac8281bf0859.gcode
2020-05-01 11:43:57,241 - tornado.access - WARNING - 404 POST /api/files/local/UM2_e9c07069-442e-4a07-90b2-ac8281bf0859.ufp.gcode (::ffff:10.0.0.10) 41.74ms
2020-05-01 11:44:18,100 - octoprint.filemanager.analysis - INFO - Analysis of entry local:UM2_e9c07069-442e-4a07-90b2-ac8281bf0859.gcode finished, needed 21.70s
`

**Comment by jneilliii** [comment]
Version 0.1.6 and up actually have this issue with the auto-start option from Cura. It still uploads the file, it just isn't able to start it automatically. The Cura plugin will be getting an update soon that fixes this, or you can downgrade to the 0.1.5 version by using the URL below in plugin manager.

https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/archive/0.1.5.zip

I will leave this ticket open until that new version is released.

**Comment by sidhant** [comment]
Thank you for the prompt response! I did downgrade to 0.1.5 and it is still giving me an issue. Its OK, until Cura plugin is updated, I will start jobs manually.

**Comment by jneilliii** [comment]
You can also follow the steps at the forum post below to test the newer Cura plugin version.

https://community.octoprint.org/t/cura-octoprint-connection-plugin/5348/224?u=jneilliii

**Comment by sidhant** [comment]
> You can also follow the steps at the forum post below to test the newer Cura plugin version.
> 
> https://community.octoprint.org/t/cura-octoprint-connection-plugin/5348/224?u=jneilliii

Cura 4.6.1 + UFP Plugin 0.1.7 + **the dev snapshot of OctoPrint Plugin** works.

**Comment by jneilliii** [comment]
Thanks for confirmation. I'm sure the Cura plugin will get updated soon with an official fix.

**Comment by leoheck** [comment]
I also came here to say the same with the same setup and versions. 
Cura's Octoprint Connection is version 3.5.12

I'm seeing this message but the file was uploaded to the Octoprint.
![image](https://user-images.githubusercontent.com/1277920/80973198-6e953e80-8df5-11ea-8340-654dd546bb4f.png)

What should I do to fix it?

**Comment by jneilliii** [comment]
You will have to wait for an official upgrade to the cura plugin, or install the development snapshot linked in the community forum post above.
