### ISSUE TITLE
Format Package Error

### ISSUE THREAD

**Issue by roverpete** [jneilliii/OctoPrint-UltimakerFormatPackage#22]
<img width="417" alt="Screenshot 2020-05-12 at 11 10 00" src="https://user-images.githubusercontent.com/65222103/81687680-12639780-9451-11ea-92b5-c835075357d1.png">
<img width="309" alt="Screenshot 2020-05-12 at 11 15 17" src="https://user-images.githubusercontent.com/65222103/81687712-17284b80-9451-11ea-8028-46f57730ec76.png">
Hi please can you help. I get this error when I install your format package remove it and cura works fine ? but it has put the file on the pi Thanks

**Comment by jneilliii** [comment]
I think there is a dev version of the cura plugin that fixes this and should be released soon. Check [here] (https://community.octoprint.org/t/cura-octoprint-connection-plugin/5348/224?u=jneilliii).
