### ISSUE TITLE
Feature Request: Display Image to the left of the list item

### ISSUE THREAD

**Issue by MaggiWuerze** [jneilliii/OctoPrint-UltimakerFormatPackage#31]
Could you add the option to place the image left of the list item instead of above?
that way we wouldn't have to increase the height of the list and stil have a thumbnail present.

**Comment by jneilliii** [comment]
I tried that when initially making this plugin and it didn't work out so well, but I will see if I can do it now with 1.5.0 because the format changed a little and might be easier to accomplish now.

**Comment by MaggiWuerze** [comment]
That's why I thought it could be done. There's a lot more horizontal space with 1.5.0
Thanks for the effort

**Comment by MaggiWuerze** [comment]
Any news?

**Comment by jneilliii** [comment]
Not yet. My initial testing made me think it was going to take a little more logic, but I've recently injured myself so development time has been reduced a bit. I will be working on this eventually and will hopefully have an update in the near future.

**Comment by MaggiWuerze** [comment]
Oh man I'm sorry. Hope you feel better soon. Maybe I'll have a look and make a PR for it.

**Comment by jneilliii** [comment]
I've expanded the plugin with the above commit and released version 0.2.3rc1 for testing. You can change your release channel in OctoPrint's Software Update settings section to `Release Candidate` and upgrade when prompted,

**Comment by MaggiWuerze** [comment]
Oh nice, I will definitely look into it and give you feedback

**Comment by MaggiWuerze** [comment]
Ok, so Octoprint does not offer me an RC. Does it take time or do I need to do something else besides setting it to RC channel? I tried forcing an updatecheck but it did not help

**Comment by jneilliii** [comment]
What version of octoprint are you running?

**Comment by jneilliii** [comment]
You can install manually by copying/pasting the url below into plugin manager > get more > ...from URL and clicking install. 

```
https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/archive/0.2.3rc1.zip
```

**Comment by MaggiWuerze** [comment]
> What version of octoprint are you running?

OctoPrint 1.5.3
Python 2.7.16
OctoPi 0.17.0

**Comment by MaggiWuerze** [comment]
> https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/archive/0.2.3rc1.zip

Will try once it finished printing

**Comment by jneilliii** [comment]
I Just fixed the release, had tagged it to the wrong branch by mistake.

**Comment by MaggiWuerze** [comment]
Cool, then I'll try that one in the morning

**Comment by MaggiWuerze** [comment]
works like a charm
![image](https://user-images.githubusercontent.com/9729962/110438765-feabb080-80b6-11eb-853b-d2d66f4e0609.png)

**Comment by jneilliii** [comment]
Perfect, thank you. I will be releasing an official version in the near future, just want to get the other last issue resolved before release.
