### ISSUE TITLE
Not working anymore after upgraded Octoprint to 1.5.2

### ISSUE THREAD

**Issue by cylstudio** [jneilliii/OctoPrint-UltimakerFormatPackage#32]
Not working anymore after upgraded Octoprint to 1.5.2, is it my settings or?

**Comment by jneilliii** [comment]
Please confirm you are running version 0.2.1 of the plugin.

**Comment by MaggiWuerze** [comment]
I am running Octoprint 1.5.2 and CuraThumbnail 0.2.1 and it works fine here.
@cylstudio maybe post some more info on your system as well as details about the nature of your problem.

**Comment by cylstudio** [comment]
Hi there, after a full reboot and restartt, it's back to normal, very strange.  Thanks for confirming it though.
