### ISSUE TITLE
Gcode Viewer and progress bar displaying incorrectly

### ISSUE THREAD

**Issue by jimmyeao** [jneilliii/OctoPrint-UltimakerFormatPackage#39]
Strange issue after installing:
![image](https://user-images.githubusercontent.com/5197831/109696992-96744080-7b85-11eb-86d8-cdeeb648015d.png)

Gcode viewer skips to 100%, 
Progress shows over 100% 
Layers show correctly

other plugins I have:
![image](https://user-images.githubusercontent.com/5197831/109697148-c7ed0c00-7b85-11eb-99d7-c418607ed893.png)

**Comment by jneilliii** [comment]
Does it do the same with Themeify disabled?

**Comment by jimmyeao** [comment]
I’ll test in the morning, printers busy at the moment :)

**Comment by jneilliii** [comment]
I just tested on my install without Themeify and everything appears to be working fine. The bottom bar progresses during layer print progress and the right bar goes up with the print. I'm not saying it's Themeify is the issue, but am currently not able to reproduce.

![image](https://user-images.githubusercontent.com/5249455/109725450-2b277000-7b7f-11eb-8b37-7801d6d14e52.png)

![image](https://user-images.githubusercontent.com/5249455/109725488-35496e80-7b7f-11eb-8af4-b666d148b1f2.png)

**Comment by jimmyeao** [comment]
Disabling themify seemed to do it, so I'll go through the themify settings one by one and see if I can narrow it down

**Comment by jimmyeao** [comment]
Ok, so now it's working with no changes other than disabling and enabling themify :/
