### ISSUE TITLE
no previews in custom folders

### ISSUE THREAD

**Issue by Goodfeat** [jneilliii/OctoPrint-UltimakerFormatPackage#41]
Hello, I noticed a problem
if you create a new folder in octoprint and put a file in it, then a preview of the model does not appear inside this folder

![image](https://user-images.githubusercontent.com/44455128/110929515-bf5db800-8373-11eb-8213-99a60deab6c4.png)

OctoPrint 1.4.2 Python 2.7.16 OctoPi 0.17.0

**Comment by jneilliii** [comment]
I can't say I'm seeing the same thing on my end. I just tested by uploading a file to a sub folder and the thumbnail loaded up just fine. Please confirm you're uploading a ufp formatted file.

![image](https://user-images.githubusercontent.com/5249455/110962195-b098e600-831e-11eb-8af1-00781f870e73.png)

**Comment by Goodfeat** [comment]
Yes it works but

you need to manually save the file with the .ufp extension so that you can save it in a separate folder. If you just copy the g-code, then it does not work(

I think I understand what is the peculiarity of this script.
as I understand it, the .ufp format splits the file into two parts
one part is a preview
the second part is directly the G-code

In this case, is it possible to somehow save the preview directly in the G-code?
I'm sure there is a way to somehow convert the image and save it in G-code using the Octoprint script
после этого выводить изображение из файла G-codethen output image from G-code file

a similar method was implemented in Prusa slicer
![image](https://user-images.githubusercontent.com/44455128/111054546-54b69480-84b9-11eb-8939-539251c2e287.png)

**Comment by jneilliii** [comment]
There is a post-processing script approach that will allow you to use Cura and the PrusaSlicer Thumbnails plugin. Follow the instructions on the comments at the link below.

https://gist.github.com/jneilliii/4034c84d1ec219c68c8877d0e794ec4e

**Comment by jneilliii** [comment]
The other option is sending the file directly from Cura using the OctoPrint Connection plugin from Cura's Marketplace. It will detect the presence of this plugin and automatically send files to OctoPrint in ufp format.

**Comment by Goodfeat** [comment]
Thanks you,
i will try this way

**Comment by Goodfeat** [comment]
unfortunately I was not able to use the script.
there is probably an error in the script and it does not appear in the list of plugins

checked on cura 4.5, 4.8, Cura Arachne_engine_alpha 99.9.0

![image](https://user-images.githubusercontent.com/44455128/111055476-ec1fe580-84c1-11eb-96ea-8b544e61a1ae.png)
![image](https://user-images.githubusercontent.com/44455128/111055513-3dc87000-84c2-11eb-8c75-a997022bedca.png)

the same on the other version of the Cura
the instruction is simple, it's hard to make a mistake, but it really doesn't work

**Comment by Goodfeat** [comment]
Found an error, the error was in the class name
P. S or rather, this is not even a mistake. the file to be downloaded has a name that differs from the name of the class

AddThumbnail.py -> AddThumbnails.py

**Comment by jneilliii** [comment]
Thanks, I've updated the file name in the gist.
