### ISSUE TITLE
Image Button Missing

### ISSUE THREAD

**Issue by mickmolloy** [jneilliii/OctoPrint-UltimakerFormatPackage#48]
Pi 3b+
Cura Thumbnails Version: 1.0.1
OctoPrint: 1.6.1 
Cura 4.10.0
OctoPrint Connection 3.5.18

I am not getting the newly added image button in octoprint following the install of the plugin , have restarted both Cura and the Pi but no change. Fresh install of the Octopi tonight

Thank You

**Comment by mickmolloy** [comment]
Note the Thumb works but I am not getting the newly added image button in octoprint,

**Comment by mickmolloy** [comment]
![image](https://user-images.githubusercontent.com/43157519/129484239-edaa950a-75e1-4e4d-9b33-92a35292c86e.png)

**Comment by jneilliii** [comment]
the button only shows up if you are not showing the image in the file list. In that case, if you click the image it should open the pop-up.

**Comment by mickmolloy** [comment]
so it will always show the thumb now?

**Comment by jneilliii** [comment]
if that option is enabled for it to show in the file list, yes. the option is in settings for you to adjust to your liking.

**Comment by jneilliii** [comment]
it only works on new files that you have uploaded since installing the plugin.

**Comment by jneilliii** [comment]
for example, this is how I have my Slicer Thumbnails plugin currently configured and the options are the same.

![image](https://user-images.githubusercontent.com/5249455/129484484-66147787-4c2b-4ae4-8bd5-876272f0875d.png)

**Comment by mickmolloy** [comment]
Thank you for the help and quick replies, the problem is solved. I just need to send the file from cure to octoprint and it works.

Cheers

Mick

**Comment by jneilliii** [comment]
Yeah, this plugin does require the format to be ufp not gcode. The cura octoprint connection plugin does that automatically for you when it sees my plugin installed.
