### ISSUE TITLE
400 Bad Request, thumbnails not displaying

### ISSUE THREAD

**Issue by rknobbe** [jneilliii/OctoPrint-UltimakerFormatPackage#49]
![image](https://user-images.githubusercontent.com/802457/139287906-467b39b1-ad5c-4bc7-bdc6-1cb50b148187.png)
![image](https://user-images.githubusercontent.com/802457/139288305-8c7ead65-50ec-418d-99c2-fb3503f80bec.png)
Running Cura Thumbnails 1.0.1 on OctoPrint 1.7.0.  Let me know what log files to upload to help diagnose.  Screenshots should help provide some context

**Comment by jneilliii** [comment]
Does same thing happen if the filename doesn't have % in it?

**Comment by rknobbe** [comment]
![image](https://user-images.githubusercontent.com/802457/139296698-821bfc21-f60f-46ce-8fa1-36b76db8309b.png)
Looks like it does not.  I'll have to tweak the Cura filename generation to avoid special characters.

Thanks!

**Comment by jneilliii** [comment]
This issue was actually a result of the above linked error from OctoPrint 1.7.0 I think. At least for now we know that the issue will be fixed in the next release, but I'll also look into fixing the issue on the plugin side when I have some time. Will be slammed for the next week or two with work.

**Comment by jneilliii** [comment]
I've added a quick fix for this, that I think may work. If you want to give it a try you can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted. 

![image](https://user-images.githubusercontent.com/5249455/139375392-f5d62117-4793-4763-8a45-c75a0b03ea00.png)

**Comment by rknobbe** [comment]
![image](https://user-images.githubusercontent.com/802457/139561072-de8e3f1c-4560-4f45-b629-bfb31c730802.png)
Success!  Thanks so much!
