### ISSUE TITLE
Does this plugin have an api to get thumbnail ?

### ISSUE THREAD

**Issue by Zoliex** [jneilliii/OctoPrint-UltimakerFormatPackage#52]
Hello sir,

Does this plugin have an api to get thumbnail ?

Have a good day

**Comment by jneilliii** [comment]
the thumbnail is included in the files API built into OctoPrint because I'm injecting the information into the metadata of the file on upload. 

https://docs.octoprint.org/en/master/api/files.html#retrieve-a-specific-file-s-or-folder-s-information
