### ISSUE TITLE
Cura not sending thumbnails in API to Octoprint

### ISSUE THREAD

**Issue by ubqtous** [jneilliii/OctoPrint-UltimakerFormatPackage#53]
Cura 4.12.1
Printer: ender 3 v2
Octoprint: 1.7.2
Cura Thumbnail: 1.0.1

![image](https://user-images.githubusercontent.com/76087970/148323196-9b6d4516-f754-4313-a7c5-4ef0b0388783.png)

Connected from Cura via OctoPrint Plugin and able to send print to OctoPrint, however the images/thumbnails in file manager don't show up. 

I looked at the API to see if the thumbnail is there, and its not.

Example of API from a file from: "http://octopi.local/api/files/local/ductfan.gcode"

{"date":1641353616,"display":"ductfan.gcode","gcodeAnalysis":{"dimensions":{"depth":180.0,"height":31.52,"width":142.166},"estimatedPrintTime":10215.891777801611,"filament":{"tool0":{"length":4104.045360000004,"volume":0.0}},"printingArea":{"maxX":142.266,"maxY":200.0,"maxZ":31.52,"minX":0.1,"minY":20.0,"minZ":0.0}},"hash":"70e30700a8993ebca0ba1ccb9f6e3fefa3817270","name":"ductfan.gcode","origin":"local","path":"ductfan.gcode","prints":{"failure":1,"last":{"date":1641369726.208919,"printTime":15902.398428114997,"success":true},"success":1},"refs":{"download":"http://octopi.local/downloads/files/local/ductfan.gcode","resource":"http://octopi.local/api/files/local/ductfan.gcode"},"size":11740616,"statistics":{"averagePrintTime":{"_default":15902.398428114997},"lastPrintTime":{"_default":15902.398428114997}},"type":"machinecode","typePath":["machinecode","gcode"]}

**Comment by fieldOfView** [comment]
Did you mean to close this issue?

Thumbnails are only available for files uploaded since you installed the plugin for OctoPrint. The Cura OctoPrint Connection plugin should detect the plugin, and start sending files over as .ufp files, which contain a thumbnail.
