### ISSUE TITLE
Feature Request - State panel thumbnail and text align options

### ISSUE THREAD

**Issue by Markalorian** [jneilliii/OctoPrint-UltimakerFormatPackage#54]
Would it be possible to add align options to the thumbnail in the state panel? Or some other way to force the text to stay underneath the thumbnail? I find that I need to scale the thumbnail to 89% or higher otherwise the text tries to squeeze in on the side, making it difficult to read. I would prefer to keep the thumbnail somewhere around 60% so that I can see more of the File List Panel underneath it. This is especially a problem when the filename uses underscores instead of spaces because it won't break up the lines and wastes even more space.

Thank you for an otherwise excellent plugin.

![Cura Thumbnails Plugin](https://user-images.githubusercontent.com/26532166/151681023-3d62e9cc-781f-4f50-8847-dd034f3410d5.png)

**Comment by jneilliii** [comment]
I'm sure there's some kind of css trick I could use to handle this, will just take some experimentation. Looks like you have UI Customizer of Themeify installed, could potentially use their advanced/custom css options to in the interim.

**Comment by jneilliii** [comment]
Added with above commit and part of version 1.0.2rc2. Change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted. 

![image](https://user-images.githubusercontent.com/5249455/151682118-5d0ea38d-1485-49ba-83b2-794ede62497e.png)

**Comment by Markalorian** [comment]
Thanks so much for such a quick response. I will install it once my current prints are done.

**Comment by Markalorian** [comment]
Worked perfectly, I just had to load a new file to see the change. Thanks again!
