### ISSUE TITLE
Question: Can I change the color of the model in thumbnail?

### ISSUE THREAD

**Issue by Kirbo** [jneilliii/OctoPrint-UltimakerFormatPackage#56]
As it reads in the title:
Can I change the color of the model in thumbnail?

Currently the models are always yellow, but if I wanted to change the color for example violet: can I do this somehow? And where should it be possible to change? In Ultimarek Cura settings somewhere or this Plugin, or...?

Thanks for the awesome plugin either way! 🙂

**Comment by jneilliii** [comment]
I'm not entirely sure it's possible in cura. I believe in PrusaSlicer the color of the image is controlled by the filament color configuration.

**Comment by fieldOfView** [comment]
In Cura the material defines the color of the model in the thumbnail (and in the viewport)

**Comment by jneilliii** [comment]
Thanks @fieldOfView

**Comment by JaneX8** [comment]
For reference: https://3dprinting.stackexchange.com/questions/21567/why-are-my-cura-generated-thumbnails-showing-in-one-flat-color-without-any-depth.
