### ISSUE TITLE
Renaming File breaks Image

### ISSUE THREAD

**Issue by a1co** [jneilliii/OctoPrint-UltimakerFormatPackage#63]
After renaming a uploaded Files the connection to the thumbnail is lost.

**Comment by jneilliii** [comment]
That's odd, the plugin does have code to account for name changes. Could you enable debug logging in OctoPrint's logging section for the plugin and try again then share octoprint.log please.

**Comment by a1co** [comment]
Reproducing failed after the latest OctoPrint update. So it may be fixed now.
