### ISSUE TITLE
Feature request: Reflect 'color change at layer' in thumbnail

### ISSUE THREAD

**Issue by JaneX8** [jneilliii/OctoPrint-UltimakerFormatPackage#64]
From: https://3dprinting.stackexchange.com/questions/21587/is-there-a-way-to-reflect-filament-color-change-in-cura-generated-thumbnails.

I want to create multi-color thumbnails that keep into account the 'Filament Change' script that was used, for example, when printing something as shown below:

![image](https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage/assets/5116641/a410941b-311c-48cb-a887-55ae9e523712)

**Comment by jneilliii** [comment]
This would be a request that has to go to Cura directly. I don't have any control of how they generate their thumbnails.
