### ISSUE TITLE
Thumbnails not shown when used Mesh tools in Cura

### ISSUE THREAD

**Issue by spanzetta** [jneilliii/OctoPrint-UltimakerFormatPackage#67]
If I split parts using Mesh Tools in Cura (latest versions) I then do not see Thumbnail in Octoprint.. even if the file is uploaded in ufp..
Can you pls check it?
Thanks

**Comment by jneilliii** [comment]
I'm no longer really working on this plugin in favor of slicer thumbnails plugin that works with cura. Disable those plugin same give that one a try. If that doesn't work then sounds like a bug with cura itself.

**Comment by spanzetta** [comment]
Thanks for the reply..
Can you pls specifiy which one is the "_slicer thumbnails plugin that works with cura_" that you mention?
I was using from over 2 years your plugin..
Thanks in advance

**Comment by jneilliii** [comment]
https://plugins.octoprint.org/plugins/prusaslicerthumbnails/

**Comment by jneilliii** [comment]
BTW...I also created that other plugin.

**Comment by spanzetta** [comment]
many thanks!!!
