### ISSUE TITLE
CURA autostart after uploading ufp file didn't work

### ISSUE THREAD

**Issue by OllisGit** [jneilliii/OctoPrint-UltimakerFormatPackage#8]
Hi @jneilliii , @fieldOfView ,

I am not sure where is the right place to raise the issue, so I mentioned both of you and also created in both githubs a ticket. Maybe it needs a "dynamic duo-solution". 
![image](https://user-images.githubusercontent.com/24205767/73683270-45fc8c00-46c2-11ea-8aa4-15abab7ee531.png)

Problem:
When the UFP Plugin is installed in octoprint the "automatically start print job" feature didn't work. After disabling the plugin the autostart is working again.
 
Analyse:
I looked into the cura-plugin, because my first assumption was that the implementation calls the upload api with the print parameter=true. So only one call for upload, select file  and start print. I thought the unzipping is not done and so the file-selection couldn't work.
But the cura-plugin send a second print call....and looking into the sourcecode I found there is some octoprint-plugin specific magic.
https://github.com/fieldOfView/Cura-OctoPrintPlugin/blob/3.5/OctoPrintOutputDevice.py#L837
```
if "PrintTimeGenius" in plugin_data:
    self._wait_for_analysis = True
```
Hey, maybe I can use this as a workaround, just installing "PrintTimeGenius" and Cura is waiting a few seconds before start printing....but that didn't help.

Maybe you have an idea, why the autoprint feature is not working.

Thanks in advance,
Olli

**Comment by fieldOfView** [comment]
This belongs here: https://github.com/fieldOfView/Cura-OctoPrintPlugin/issues/146
